let imgJson = [
    {id:1, name: 'Bola adidas', img: 'imagens/Home/main/bolaAdidas.png', price: 130 , id2: 'Variados'},
    {id:2, name: 'Corda', img: 'imagens/Home/main/corda.png', price: 39 , id2: 'Variados'},
    {id:3, name: 'Creatina', img: 'imagens/Home/main/creatinaIntegral.png', price: 55, id2: 'Variados'},
    {id:4, name: 'Básica feminina', img: 'imagens/Home/main/básicaFeminina.png', price: 132.39, id2: 'Moda'},
    {id:5, name: 'Esteira', img: 'imagens/Home/main/esteira.png', price: 530.50, id2: 'Variados'},
    {id:6, name: 'Whey', img: 'imagens/Home/main/max.png', price: 120, id2: 'Variados'},
    {id:7, name: 'Pasta de amendoim', img: 'imagens/Home/main/pastaAmendoim.png', price: 32.99, id2: 'Variados'},
    {id:8, name: 'Camisa da seleção brasileira', img: 'imagens/Home/main/seleçãoBrasileira.png', price: 259, id2: 'Moda'},
    {id:9, name: 'Short Adidas', img: 'imagens/Home/main/shortAdidas.png', price: 89.99, id2: 'Moda'},
    {id:11, name: 'Supino', img: 'imagens/Home/main/supino.png', price: 800, id2: 'Variados'},
    {id:12, name: 'Tênis feminino Nike', img: 'imagens/Home/main/tenisFeminino.png', price: 249.99, id2: 'Calçado'},
    {id:13, name: 'Short térmico Nike', img: 'imagens/Home/main/termicaNike.png', price: 90, id2: 'Moda'},
    {id:14, name: 'Vitamina B12', img: 'imagens/Home/main/vitaminaB12.png', price: 55, id2: 'Variados'},
    {id:15, name: 'YoPro', img: 'imagens/Home/main/YoPro.png', price: 5.99, id2: 'Variados'},
    {id:16, name: 'Conjunto do Flamengo', img: 'imagens/Home/main/Flamengo.png', price: 329.99, id2: 'Moda'},
    {id:17, name: 'Chuteira Nike', img: 'imagens/Home/slidePrincipal/Esporte/chuteira.png', price: 329.99, id2: 'Calçado'},
    {id:18, name: 'Escada', img: 'imagens/Home/slidePrincipal/Esporte/Escada.png', price: 329.99, id2: 'Calçado'},
    {id:19, name: 'Camisa da seleção brasileira', img: 'imagens/Home/slidePrincipal/Moda/brasil.png', price: 329.99, id2: 'Calçado'},
    {id:20, name: 'Jaqueta', img: 'imagens/Home/slideModa/oculosCiclista.png', price: 329.99, id2: 'Calçado'},
    {id:21, name: 'Tênis Lakers', img: 'imagens/Home/slidePrincipal/Moda/tenis.png', price: 329.99, id2: 'Calçado'},
    {id:22, name: 'Barrinha de proteína', img: 'imagens/Home/slidePrincipal/Suplemento/barrinha.png', price: 329.99, id2: 'Calçado'},
    {id:23, name: 'Combo IntegralMédica', img: 'imagens/Home/slidePrincipal/Suplemento/comboInt.png', price: 329.99, id2: 'Calçado'},
    {id:24, name: 'Combo Max Titanium', img: 'imagens/Home/slidePrincipal/Suplemento/comboMax1.png', price: 329.99, id2: 'Calçado'},
    {id:25, name: 'Combo Max Titanium', img: 'imagens/Home/slidePrincipal/Suplemento/comboMax2.png', price: 329.99, id2: 'Calçado'},
    {id:26, name: 'Combo Probiótica', img: 'imagens/Home/slidePrincipal/Suplemento/comboProbiotica.png', price: 329.99, id2: 'Calçado'},
    {id:27, name: 'Whey Max Titanium', img: 'imagens/Home/slidePrincipal/Suplemento/max.png', price: 329.99, id2: 'Calçado'},
    {id:28, name: 'Chinelo da Nike', img: 'imagens/Home/slideModa/chineloNike.png', price: 329.99, id2: 'Calçado'},
    {id:29, name: 'Tênis Adidas', img: 'imagens/Home/slideModa/adidasJoger.png', price: 329.99, id2: 'Calçado'},
    {id:30, name: 'Chinelo da Nike', img: 'imagens/Home/slideModa/poloBoss.png', price: 329.99, id2: 'Calçado'},
    {id:31, name: 'Apple Watch', img: 'imagens/Home/slideModa/apple.png', price: 329.99, id2: 'Calçado'},
]